api_key: "your_api_key"
api_secret: "your_api_secret"

symbol: "XRP_USDT"
trade_amount: 20

buy_threshold: -0.02 # -1% drop in 1 minute
sell_threshold: 0.005 # +0.5% rise in 1 minute

check_interval: 10 # check every 10 seconds
min_usdt_balance: 10
min_trade_usdt: 3
